### ISSUE TITLE
Branche par défaut

### ISSUE THREAD

**Issue by florentbarriol** [m6-workshops/kata-1-team-cytron#1]
Hello,
J'ai fait une erreur, j'ai pushé ma branche alors qu'on avait pas créé encore de branche master...
Je vous propose que je crée une branche master et qu'on merge chacune de nos branches dedans.
Qu'est ce que vous en pensez ?

**Comment by clement-berard** [comment]
j'ai fais pareil ^^

**Comment by clement-berard** [comment]
mais en vrai on aurait du faire ca direct, mais qui l'aurait fait toussa toussa 🙃

**Comment by florentbarriol** [comment]
Ouais :/
Mais bon la précipitation et tout

**Comment by clement-berard** [comment]
ok on est bon !

**Comment by clement-berard** [comment]
comment on nomme notre fihcier ? `histoire.md` ???

**Comment by florentbarriol** [comment]
Ok 👍 
Mais comment on les préviens de venir voir ici ? :D

**Comment by clement-berard** [comment]
donne lui un coup de pied ahah

**Comment by VirgileLyon** [comment]
Bonjour

**Comment by VirgileLyon** [comment]
Du coup on fait comment? Y'a un truc a Pull?

**Comment by florentbarriol** [comment]
je pousse `histoire.md` sur master et on commence à créer les PR ?
@clement-berard tu crées une PR pour la 4eme de couverture ?

**Comment by clement-berard** [comment]
du coup il faut un fichier par personne ? quand ils disent "il faut un fichier pour la 4eme de couverture"

**Comment by florentbarriol** [comment]
Non, il faut un seul  fichier pour l'histoire et un pour la 4eme de couv

**Comment by VirgileLyon** [comment]
ok reçu pour histoire.md

**Comment by sowakillian** [comment]
On les nomme comment les fichiers du coup ? .md ?

**Comment by florentbarriol** [comment]
J'ai poussé sur master, vous pouvez rebase vos branches ;)

**Comment by clement-berard** [comment]
qui fait la 4eme ?

**Comment by clement-berard** [comment]
j'ai merge sur master, pensez rebase

**Comment by clement-berard** [comment]
je fais la 4eme ok ?

**Comment by clement-berard** [comment]
qui fait la photo ???

**Comment by clement-berard** [comment]
qui fait le titre ?

**Comment by florentbarriol** [comment]
je cherche la photo :)

**Comment by clement-berard** [comment]
j'ai fais la 4eme avec vos textes, dite moi quand je merge ;)

**Comment by clement-berard** [comment]
ou si y'a des modifs que je dois apporter

**Comment by VirgileLyon** [comment]
C'est bon de mon coté ma partie est envoyée.

**Comment by clement-berard** [comment]
du coup non ca va pas Virgile, il faut tout mettre dans le histoire.md

**Comment by VirgileLyon** [comment]
merde

**Comment by florentbarriol** [comment]
je merge l'intro

**Comment by clement-berard** [comment]
je vais pas tarder a merger le summary

**Comment by florentbarriol** [comment]
j'ai mergé l'intro, pensez à rebase votre master :)

**Comment by florentbarriol** [comment]
il faut nommer comment l'illustration ?

**Comment by clement-berard** [comment]
resumé mergé, pensez a rebase ;)

**Comment by clement-berard** [comment]
je sais pas, `illustration` ?

**Comment by florentbarriol** [comment]
@VirgileLyon @sowakillian , créez vos PRs et mergez chacun votre tour dans histoire.md ;)

**Comment by clement-berard** [comment]
il reste pas bcp de temps 😱

**Comment by sowakillian** [comment]
C'est bon pour la PR, je merge direct ?

**Comment by florentbarriol** [comment]
Faites un squash and merge quand vous mergez ^^

**Comment by clement-berard** [comment]
@sowakillian non en fait faut mettre ton bout de texte dans `histoire.md`

**Comment by VirgileLyon** [comment]
J'ai push ma part3 mais j'arrive pas a la mettre dans histoire

**Comment by florentbarriol** [comment]
je merge l'image

**Comment by florentbarriol** [comment]
@VirgileLyon C'est quoi le problème ? dis nous ? on tente le tout pour le tout !!

**Comment by VirgileLyon** [comment]
J'ai push ma part3 vous l'a voyer bien dans le repo?

**Comment by sowakillian** [comment]
J'ai mergé dans histoire c'est bon ma partie apparaît

**Comment by VirgileLyon** [comment]
part3.md il y a 4 minutes

**Comment by florentbarriol** [comment]
@VirgileLyon tu pousse sur `master` là ^^
